---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: centos-7.1
    provisioner:
      require_chef_omnibus: "12.8" # cdh mysql dependency doesn't support chef 13

suites:
  - name: default
    run_list:
      - recipe[certbot-cdh::default]
    attributes:
