name 'certbot-cdh'
maintainer 'Felicity Ratcliffe'
maintainer_email 'fratcliffe@inviqa.com'
license 'apache2'
description 'Installs/Configures certbot-cdh'
long_description 'Installs/Configures certbot-cdh'
version '0.1.0'

issues_url 'https://github.com/inviqa/chef-certbot-cdh/issues'
source_url 'https://github.com/inviqa/chef-certbot-cdh'

depends 'nginx', '< 3'
depends 'cron'
depends 'yum-epel'
depends 'config-driven-helper', '~> 2.5'
